image: maven:3

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -s ci/settings.xml clean test
  custom:
    release:
      - step:
          caches:
            - maven
          script:
            - git config --global user.email "nobody@atlassian.com"
            - git config --global user.name "Release"
            - git checkout -b release_branch
            - mvn -s ci/settings.xml -B release:prepare -DscmCommentPrefix="[skip ci]" -Pupdate-changelog
            - mvn -s ci/settings.xml -B release:perform -Dgoals=install -Darguments="-Dmaven.deploy.skip=true"
            - git checkout master
            - git pull origin master
            - git merge --no-edit release_branch
            - git push origin master
            - git push origin ":release_branch"
