image: maven:3

pipelines:
  default:
    - step:
        script:
          - mvn -s ci/settings.xml clean test
  custom:
    prepare-release:
      - step:
          script:
            - git config --global user.email "nobody@atlassian.com"
            - git config --global user.name "Release"
            - mvn -s ci/settings.xml -B release:prepare -Dusername=$BITBUCKET_USERNAME -Dpassword=$BITBUCKET_PASSWORD -DscmCommentPrefix="[skip ci]"
            - mvn -s ci/settings.xml -B release:perform -Dgoals=install
