image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn -V -s ci/settings.xml clean test
  custom:
    release:
      - step:
          caches:
            - maven
          script:
            - git --version
            - git config --global user.email "nobody@atlassian.com"
            - git config --global user.name "Release"
            - git checkout -b release_branch
            - mvn -V -s ci/settings.xml -B javadoc:javadoc
            - python ci/changelog.py
            - git add CHANGES.md
            - git commit CHANGES.md -m "[skip ci] Update changelog"
            - mvn -s ci/settings.xml -B release:prepare -DscmCommentPrefix="[skip ci]"
            - mvn -s ci/settings.xml -B release:perform
            - git checkout master
            - git pull origin master
            - git merge --no-edit release_branch
            - git push origin master
            - git push origin ":release_branch"
